### ISSUE TITLE
DISCORD WEBHOOK HELP SETUP

### ISSUE THREAD

**Issue by pglandrew** [Davnit/StealthBotScripts#4]
Hello i'm trying to setup this => https://github.com/Davnit/StealthBotScripts/blob/master/DiscordHook.txt

but i dont have any ideea what i do wrong sinces no info how to setup it

please help!

i added the webhook and channel but seams is not working

**Comment by Davnit** [comment]
I've added more detailed setup instructions to the [wiki page for this script](
https://github.com/Davnit/StealthBotScripts/wiki/DiscordHook).

**Comment by pglandrew** [comment]
@Davnit 

i added this on scripts.ini

[DiscordHook]
Hook=[REDACTED]
ShowJoins: true
Channel: If set, only events from the specified channel will be sent.

and not working

what i do wrong?

and yes is a specific channel already set in webhook called euro-games but is not working :(

help please

**Comment by Davnit** [comment]
For ShowJoins, the T in true needed to be capitalized.
For Channel, the value should be the name of the Battle.net channel you want messages sent FROM. If you want messages sent from wherever your bot happens to be then just don't include that line.

**Comment by pglandrew** [comment]
i just want he to announce games in my discord server in channel euro-games @Discord server
in the webook already i select that and i add the lines in scripts.ini but not working


and wich value shold be battle.net ?
can you give a full example and just edit it ? please

and what means "capitalized" about this: For ShowJoins, the T in true needed to be capitalized.?

**Comment by pglandrew** [comment]
[DiscordHook]
Hook=[REDACTED]
ShowJoins: true
Channel: OP D2Services (this is channel on diablo 2 game)

euro-games is the channel on discord where i want to announce games

**Comment by pglandrew** [comment]
i got also this error


"[16:37:47] Scripting runtime error #-2147221020 in DiscordHook: (line 63; column 0)
 [16:37:47] Invalid syntax

 [16:37:47] Scripting runtime error #-2147221020 in DiscordHook: (line 63; column 0)
 [16:37:47] Invalid syntax
"

**Comment by Davnit** [comment]
I don't know about the error unless you've somehow modified the script. Try re-downloading it (right click on the 'Raw' button and use the save as option).

Make sure there is only one line that says `[DiscordHook]` in your scripts.ini file, and everything should go directly below that (before any other line with brackets). You also need to use `=` instead of `:`.

```
[DiscordHook]
Hook=your hook URL
ShowJoins=True
Channel=OP D2Services
```

**Comment by pglandrew** [comment]
i dont modifiy nothing is default from github

where i add this? => http://prntscr.com/pq875f

the webhook? or is only need to create on discord ?

**Comment by Davnit** [comment]
The name in your screenshot is just what you want it to show up as on Discord. The only thing you need from that screen is the webhook URL.

**Comment by pglandrew** [comment]
yeah i fixed :) ty for reply cheers!
