### ISSUE TITLE
Discord webhook

### ISSUE THREAD

**Issue by XoniBlue** [Davnit/StealthBotScripts#5]
hey is there a way to have the webhook announce what games are being made and tracked?

**Comment by Davnit** [comment]
If you have a separate script that handles the tracking and announcing you could modify it to call `Scripts("DiscordHook").Send(Username, Message)` in addition to or instead of whatever it calls now. You'd have to find that in the other script and modify it yourself though.

**Comment by XoniBlue** [comment]
> If you have a separate script that handles the tracking and announcing you could modify it to call `Scripts("DiscordHook").Send(Username, Message)` in addition to or instead of whatever it calls now. You'd have to find that in the other script and modify it yourself though.

i actually was able to just modify the bcp to not whisper announce the games. but actually announce, and its working rather nice. im having a whole set of other issues. ive no idea how to tackle. tho lol thank you for your quick response.   have you got a discord link or another way to chat thats not this?

**Comment by Davnit** [comment]
https://discord.gg/u87WVeu
